version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DATABASE_URL=postgres://dnjones:idk45107@db:5432/RachelDB"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=RachelDB
      - POSTGRES_USER=dnjones
      - POSTGRES_PASSWORD=idk45107

volumes:
  postgres_data:
